### ISSUE TITLE
1.19.1 sound event problem[Fabric]

### ISSUE THREAD

**Issue by Faris90** [samolego/Taterzens#116]
**Describe the bug**

**Platform(s)**

- [x] Fabric
- [] Forge

**Environment(s)**

- [] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.19.1
* Taterzens 1.11.0

**To Reproduce**
1. Disable invulnerability
2. Damage the NPC anyway
3. See Error

**Expected behavior**
Not get kicked out

**Logs**

<details>
  <summary>Logs</summary>
`[14:30:25] [Netty Epoll Server IO #0/ERROR]: Error receiving packet 96
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@3457dad5' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
	at net.minecraft.class_2540.method_42065(class_2540.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.class_2767.method_11052(class_2767.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:201) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[14:30:25] [Server thread/INFO]: Named entity TaterzenNPC['Morby'/257, l='ServerLevel[world]', x=-507.56, y=70.00, z=-230.44] died: Morby fell out of the world
[14:30:25] [Server thread/INFO]: [TheHUB1: Killed Morby]
[14:30:25] [Server thread/INFO]: TheHUB1 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@3457dad5' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
[14:30:25] [Server thread/INFO]: TheHUB1 left the game
[14:30:33] [Server thread/INFO]: TheHUB1[/135.0.24.199:52769] logged in with entity id 712 at (-509.534704447955, 70.0, -230.17622806396122)
[14:30:33] [Server thread/INFO]: TheHUB1 joined the game
[14:32:34] [Server thread/INFO]: [TheHUB1: Applied effect Night Vision to TheHUB1]
[14:32:38] [Server thread/INFO]: [TheHUB1: Applied effect Night Vision to TheHUB1]
[14:33:53] [Server thread/INFO]: [TheHUB1: Modified entity data of Dorbo]
[14:33:55] [Netty Epoll Server IO #2/ERROR]: Error receiving packet 96
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@64e47770' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
	at net.minecraft.class_2540.method_42065(class_2540.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.class_2767.method_11052(class_2767.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10761(class_2535.java:201) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[14:33:55] [Server thread/INFO]: TheHUB1 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@64e47770' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]`
</details>

**Comment by Faris90** [comment]
No chat reports is probably causing this

**Comment by Faris90** [comment]
@samolego idk why... It seems to happen when server side on vanilla client

**Comment by samolego** [comment]
I haven't found a fix for this yet, it's really weird.

**Comment by samolego** [comment]
Are you using any other mods? It doesn't happen with taterzens only in dev env ...

**Comment by Kloenk** [comment]
also happens on 1.19

(server config with mod list (but a nix file): https://cyberchaos.dev/kloenk/nix/-/blob/021f57a1e99f531a3266b806ff204a154b3a34c1/configuration/hosts/iluvatar/minecraft.nix#L39)

**Comment by Kloenk** [comment]
Stacktrace reads like something related to some registries:

<details>
<summary>Stacktrace</summary>
<pre><code>
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@5198cb5c' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
	at net.minecraft.class_2540.method_42065(class_2540.java:147) ~[server-intermediary.jar:?]
	at net.minecraft.class_2767.method_11052(class_2767.java:47) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:45) [server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:14) [server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-codec-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) [netty-transport-4.1.76.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.76.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-common-4.1.76.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) [netty-transport-classes-epoll-4.1.76.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.76.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.76.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[23:21:14] [Server thread/INFO]: Kloenk lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@5198cb5c' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
</code></pre>
</details>

**Comment by sisby-folk** [comment]
Hi hello there! just wanted to give a bit more information on this one.

using `/npc remove` will kick every client on the server due to this issue.

**Comment by negapli** [comment]
Same here in 1.19.2 : I having the same problem with only fabric api and taterzens-1.11.0-fabric on my mod folder

` Named entity TaterzenNPC['Hello world!'/316, l='ServerLevel[world]', x=14.12, y=81.00, z=-11.33] died: Hello world! fell out of the world
[22:27:09] [Netty Server IO #2/ERROR]: Error receiving packet 96
java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@1f04b678' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
        at net.minecraft.class_2540.method_42065(class_2540.java:147) ~[server-intermediary.jar:?]
        at net.minecraft.class_2767.method_11052(class_2767.java:47) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.method_10838(class_2545.java:45) ~[server-intermediary.jar:?]
        at net.minecraft.class_2545.encode(class_2545.java:14) ~[server-intermediary.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.77.Final.jar:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.77.Final.jar:?]
        at net.minecraft.class_2535.method_36942(class_2535.java:209) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10761(class_2535.java:201) ~[server-intermediary.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[22:27:09] [Server thread/INFO]: nega_mario lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.class_3414@1f04b678' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]
[22:27:09] [Server thread/INFO]: nega_mario left the game`

Serverlog

**Comment by negapli** [comment]
update : it's only doing this on server not on solo

**Comment by negapli** [comment]
i figured out how to fix it : 
1)Create you npc
2)type this command : npc edit tags allowSounds false


TADA ! for some reason the server try to plays sound if a npc get kill

**Comment by PortadorDeluz** [comment]
effectively the problem is solved as proposed by @negapli, my question is, does that imply that the taterzen will not make any sound?

**Comment by samolego** [comment]
Yes that means that they won't make any sounds

**Comment by PortadorDeluz** [comment]
so it is not a definitive solution.

**Comment by PortadorDeluz** [comment]
In addition, every time I leave the server, the option is reactivated, and it throws the error again.

**Comment by negapli** [comment]
i llok a little bit in the config.json and if you want a "fix" just making blank the : " "death_sounds" and "hurt_sounds" too nothing. The npc gonna be silence but fix the issue

**Comment by PortadorDeluz** [comment]
Works!, but it would be nice if it was corrected as it decreases the immersion to see all the taterzens in silence.
