### ISSUE TITLE
Cannot Create NPC - Spell Engine/Power Mod Conflict [Fabric]

### ISSUE THREAD

**Issue by AetheriMC** [samolego/Taterzens#132]
**Describe the bug**

**Platform(s)**

- [x] Fabric
- [] Forge

**Environment(s)**

- [x] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.19.2
* Taterzens 1.11.1

**To Reproduce**
1. Taterzens with the [Spell Engine Mod](https://www.curseforge.com/minecraft/mc-mods/spell-engine) and [Spell Power Attributes Mod](https://www.curseforge.com/minecraft/mc-mods/spell-power)
2. Use the command /npc create
3. Error An unexpected error occured trying to execute that command occurs. Upon hover, "Duplicate value id for 15!"

**Additional context**
With ~200 mods installed, I essentially removed/added mods until narrowing the issue down to these two.

**Comment by samolego** [comment]
That's the same issue as Galosphere ...

**Comment by AetheriMC** [comment]
Thanks for responding. Does that imply that the issue needs to be reported to the creator of the mods I listed then instead of here? I had just assumed that the issue was on this end.

**Comment by samolego** [comment]
I'm not sure why it's happening, but it's probably on my side since it has happened with other mods as well.

**Comment by AetheriMC** [comment]
Does this help? It's part of a CTD I encountered when trying to use the Identity menu with Taterzens installed on a single player. The crash itself isn't relevant and I've already resolved the problem going forward after reading through the issue tracker, but in the log there's mention of the "Duplicate id value for 15!".

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-02-23 16:22:38
Description: Unexpected error

java.lang.IllegalArgumentException: Duplicate id value for 15!
	at net.minecraft.class_2945.method_12784(class_2945.java:82)
	at net.minecraft.class_1309.handler$hlp001$initDataTracker_TAIL_SpellEngine_SyncEffects(class_1309.java:42670)
	at net.minecraft.class_1309.method_5693(class_1309.java:291)
	at net.minecraft.class_1308.method_5693(class_1308.java:269)
	at net.minecraft.class_1297.<init>(class_1297.java:292)
	at net.minecraft.class_1309.<init>(class_1309.java:244)
	at net.minecraft.class_1308.<init>(class_1308.java:135)
	at net.minecraft.class_1314.<init>(class_1314.java:14)
	at org.samo_lego.taterzens.npc.TaterzenNPC.<init>(TaterzenNPC.java:187)
	at net.minecraft.class_1299.method_5883(class_1299.java:487)
	at draylar.identity.api.variant.IdentityType.getAllTypes(IdentityType.java:91)
	at draylar.identity.screen.IdentityScreen.populateRenderEntities(IdentityScreen.java:217)
	at draylar.identity.screen.IdentityScreen.<init>(IdentityScreen.java:53)
	at draylar.identity.impl.tick.MenuKeyPressHandler.tick(MenuKeyPressHandler.java:17)
	at draylar.identity.impl.tick.MenuKeyPressHandler.tick(MenuKeyPressHandler.java:9)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy2/jdk.proxy2.$Proxy161.tick(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$2(EventHandlerImpl.java:54)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$dlk000$onStartTick(class_310.java:14969)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by samolego** [comment]
Thanks, that might help

**Comment by GLopzu** [comment]
Since december i have been seeing same bug :/

**Comment by droodgit** [comment]
I can report that I also have the same bug with precisely the same conditions. I'm unsure precisely where these two mods overlap but "duplicate value for id 15!" is consistent.

**Comment by Sultansmooth** [comment]
Also having this problem sadly

**Comment by DEAFG0AT** [comment]
I'm having the same bug on Fabric 1.19.2, I think it may be caused by Spell Engine but here is my modlist anyway
[modlist.txt](https://github.com/samolego/Taterzens/files/12234590/modlist.txt)
