### ISSUE TITLE
PeacefulDamage can't 'hurt' - causes a Crash in 1.20.1

### ISSUE THREAD

**Issue by DrCo** [samolego/Taterzens#150]
**Describe the bug**
It looks like 'hurt' isn't defined or bound well somewhere. A partial crashed log is included below. The targeting of an entity might have changed in the latest version? I'm not sure if this has to do with a json error or a change somewhere in how a Mixin is read by sponge or fabric.

**Platform(s)**

- [x] Fabric
- [ ] Forge
 
**Environment(s)**

- [x] Singleplayer
- [  ] Server (hopefully)

**Versions**
* Fabric 1.21.1
* GDLauncher 1.1.30
* taterzens-fabric-1.20-1.11.5.jar

**To Reproduce**
1. Downloaded taterzens-fabric-1.20-1.11.5.jar from Modrinth
2. Dropped the file into mods directory
3. Minecraft instance crashed before loading a splash screen

**Expected behavior**
Expected Taterzens to work like Citizens for Fabric, in a lobby.

**Logs**

[19:17:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/t/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next/datastore/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:17:39] [main/INFO]: Compatibility level set to JAVA_16
[19:17:39] [main/INFO]: Compatibility level set to JAVA_17
[19:17:39] [main/WARN]: Reference map 'taterzens-fabric-1.20-rc1-refmap.json' for taterzens.common.mixins.json could not be read. If this is a development environment you can ignore this message
[19:17:40] [main/WARN]: Error loading class: net/minecraft/server/level/ChunkMap$TrackedEntity (java.lang.ClassNotFoundException: net/minecraft/server/level/ChunkMap$TrackedEntity)
[19:17:40] [main/WARN]: @Mixin target net.minecraft.server.level.ChunkMap$TrackedEntity was not found taterzens.common.mixins.json:accessors.AEntityTrackerEntry from mod taterzens
[19:17:40] [main/ERROR]: Mixin apply for mod taterzens failed taterzens.common.mixins.json:player.PlayerMixin_PeacefulDamage from mod taterzens -> net.minecraft.class_1657: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on enableTaterzenPeacefulDamage could not find any targets matching 'hurt' in net.minecraft.class_1657. No refMap loaded. [PREINJECT Applicator Phase -> taterzens.common.mixins.json:player.PlayerMixin_PeacefulDamage from mod taterzens -> Prepare Injections ->  -> handler$zlf000$taterzens$enableTaterzenPeacefulDamage(Lnet/minecraft/class_1282;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on enableTaterzenPeacefulDamage could not find any targets matching 'hurt' in net.minecraft.class_1657. No refMap loaded. [PREINJECT Applicator Phase -> taterzens.common.mixins.json:player.PlayerMixin_PeacefulDamage from mod taterzens -> Prepare Injections ->  -> handler$zlf000$taterzens$enableTaterzenPeacefulDamage(Lnet/minecraft/class_1282;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]

**Additional context**
Tried with and without DisguiseLib, but the loader still complains with
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explaination

**Comment by samolego** [comment]
Update to 1.11.6, it should be fixed there
