### ISSUE TITLE
`/npc create` without player name errors out and does not visually create NPC

### ISSUE THREAD

**Issue by James103** [samolego/Taterzens#16]
When you run `/npc create` without any further arguments, the command prints "An unexpected error occurred trying to execute that command" to chat and the following to the game log:
```
[01:25:19] [main/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ''.
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9) ~[?:?]
	at net.minecraft.scoreboard.Scoreboard.removePlayerFromTeam(Scoreboard:236) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onTeam(ClientPlayNetworkHandler:2151) ~[?:?]
	at net.minecraft.network.packet.s2c.play.TeamS2CPacket.apply(TeamS2CPacket:122) ~[?:?]
	at net.minecraft.network.packet.s2c.play.TeamS2CPacket.apply(TeamS2CPacket:16) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[01:25:19] [main/INFO]: [CHAT] An unexpected error occurred trying to execute that command
```

Either the command should create an NPC based on your avatar or `/npc create` should be changed to require a player name to be input.

Modlist (MC 1.16.5):
```
Mods:
  [✔️] cloth-config-4.11.26-fabric
  [✔️] disguiselib-1.0.3-fabric
  [✔️] fabric-api-0.34.6+1.16
  [✔️] mobdisguises-1.0.1-fabric
  [✔️] modmenu-1.16.9
  [✔️] notenoughcrashes-3.2.0-fabric
  [✔️] taterzens-1.1.0-fabric
```

**Comment by samolego** [comment]
Fixed in `1.1.1`
