### ISSUE TITLE
Bug report [Forge / Fabric]

### ISSUE THREAD

**Issue by VinceKezel** [samolego/Taterzens#169]
**Describe the bug**
Can't create any NPCs... just get error messages

**Platform(s)**
- [x] Fabric 0.14.22

**Environment(s)**
- [x] Server

**Versions**
* Minecraft 1.20.1
* Taterzens 1.11.7

**To Reproduce**
1. Launch server
2. run any npc command

**Expected behavior**
NPC created

**Logs**
[modlist.txt](https://github.com/samolego/Taterzens/files/12778030/modlist.txt)

important bit:

```[15:07:33 ERROR]: Command exception: /npc create
java.lang.NullPointerException: Cannot invoke "com.mojang.authlib.GameProfile.getId()" because "$$0" is null
	at net.minecraft.class_4844.method_43343(class_4844.java:98) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.<init>(class_1657.java:209) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.<init>(class_3222.java:266) ~[server-intermediary.jar:?]
	at org.samo_lego.taterzens.npc.TaterzenNPC.constructFakePlayer(TaterzenNPC.java:211) ~[taterzens-fabric-1.20.1-1.11.7.jar:?]
	at org.samo_lego.taterzens.npc.TaterzenNPC.method_5841(TaterzenNPC.java:418) ~[taterzens-fabric-1.20.1-1.11.7.jar:?]
	at net.minecraft.class_1309.handler$bkn000$galosphere$G$defineSynchedData(class_1309.java:16157) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5693(class_1309.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.method_5693(class_1308.java:267) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.<init>(class_1297.java:297) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.<init>(class_1309.java:246) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.<init>(class_1308.java:133) ~[server-intermediary.jar:?]
	at net.minecraft.class_1314.<init>(class_1314.java:14) ~[server-intermediary.jar:?]
	at org.samo_lego.taterzens.npc.TaterzenNPC.<init>(TaterzenNPC.java:160) ~[taterzens-fabric-1.20.1-1.11.7.jar:?]
	at org.samo_lego.taterzens.npc.TaterzenNPC.<init>(TaterzenNPC.java:146) ~[taterzens-fabric-1.20.1-1.11.7.jar:?]
	at org.samo_lego.taterzens.api.TaterzensAPI.createTaterzen(TaterzensAPI.java:135) ~[taterzens-fabric-1.20.1-1.11.7.jar:?]
	at org.samo_lego.taterzens.api.TaterzensAPI.createTaterzen(TaterzensAPI.java:154) ~[taterzens-fabric-1.20.1-1.11.7.jar:?]
	at org.samo_lego.taterzens.commands.NpcCommand.spawnTaterzen(NpcCommand.java:401) ~[taterzens-fabric-1.20.1-1.11.7.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
	at net.minecraft.class_2170.redirect$zde000$architectury$performCommand(class_2170.java:1045) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:287) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_45010(class_3244.java:1341) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_44356(class_3244.java:1321) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5386(class_1255.java:67) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by samolego** [comment]
Galosphere is not compatible with taterzens, sorry.
