### ISSUE TITLE
Got an issue when I use Fabric Tailor with Taterzens

### ISSUE THREAD

**Issue by HEYMANCXN** [samolego/Taterzens#24]
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/samo_lego/taterzens/interfaces/TaterzenEditor
	at org.samo_lego.fabrictailor.compatibility.TaterzensCompatibility.setTaterzenSkin(TaterzensCompatibility.java:11)
	at org.samo_lego.fabrictailor.util.SkinFetcher.setSkinFromReply(SkinFetcher.java:185)
	at org.samo_lego.fabrictailor.util.SkinFetcher.fetchSkinByUrl(SkinFetcher.java:95)
	at org.samo_lego.fabrictailor.command.SkinCommand.setSkinUrl(SkinCommand.java:88)
	at org.samo_lego.fabrictailor.command.SkinCommand.lambda$register$1(SkinCommand.java:34)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
	at net.minecraft.class_2170.redirect$zjo000$performCommand(class_2170.java:547)
	at net.minecraft.class_2170.method_9249(class_2170.java:251)
	at net.minecraft.class_3244.method_14370(class_3244.java:1239)
	at net.minecraft.class_3244.method_31286(class_3244.java:1223)
	at net.minecraft.class_3244.method_12048(class_3244.java:1206)
	at net.minecraft.class_2797.method_12115(class_2797.java:30)
	at net.minecraft.class_2797.method_11054(class_2797.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:783)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:167)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:759)
	at net.minecraft.class_1255.method_18857(class_1255.java:134)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:744)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ClassNotFoundException: org.samo_lego.taterzens.interfaces.TaterzenEditor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 27 more

Here's mod:taterzens-1.2.0-fabric,fabrictailor-1.6.1

**Comment by samolego** [comment]
Uh, yeah, I changed some things, I should update FabricTailor ...

**Comment by misterslime** [comment]
I think I got the same issue:

[crash-2021-07-19_17.16.10-server.txt](https://github.com/samolego/Taterzens/files/6844394/crash-2021-07-19_17.16.10-server.txt)
