### ISSUE TITLE
`/npc action interact` fails for certain blocks, such as inventories and lecterns

### ISSUE THREAD

**Issue by James103** [samolego/Taterzens#41]
When running `/npc action` for an NPC to interact with any of the following blocks, the corresponding error message is generated and the command fails:
<details>

<summary> Exception on `/npc action interact` for Chest, Crafting Table, Furnace, Hopper, Dropper, Dispenser </summary>

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_17355(net.minecraft.class_3908)" because "â˜ƒ" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.37) ~[?:?]
	at net.minecraft.block.ChestBlock.onUse(ChestBlock:208) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:938) ~[?:?]
	at org.samo_lego.taterzens.npc.TaterzenNPC.interact(TaterzenNPC.java:1293) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand.lambda$interactWithBlock$2(ActionCommand.java:42) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand$$Lambda$7179/0x00000000f2c6eef0.accept(Unknown Source) ~[?:?]
	at org.samo_lego.taterzens.commands.NpcCommand.selectedTaterzenExecutor(NpcCommand.java:105) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand.interactWithBlock(ActionCommand.java:41) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand$$Lambda$5310/0x00000000f21186b8.run(Unknown Source) ~[?:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.server.command.CommandManager.execute(CommandManager:251) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.executeCommand(ServerPlayNetworkHandler:1222) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handleMessage(ServerPlayNetworkHandler:1206) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onGameMessage(ServerPlayNetworkHandler:1189) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:30) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:7) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.class_2600$$Lambda$6736/0x00000000f284ef88.run(Unknown Source) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:788) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:164) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:770) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:764) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:749) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zmi000$modifiedRunLoop(MinecraftServer:4399) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$6167/0x00000000cd699b90.run(Unknown Source) [intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:883) [?:?]
```

</details>

<details>

<summary> Exception on `/npc action interact` for Lectern, Composter, Respawn Anchor </summary>

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_5998(net.minecraft.class_1268)" because "â˜ƒ" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.37) ~[?:?]
	at net.minecraft.block.LecternBlock.onUse(LecternBlock:280) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:938) ~[?:?]
	at org.samo_lego.taterzens.npc.TaterzenNPC.interact(TaterzenNPC.java:1293) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand.lambda$interactWithBlock$2(ActionCommand.java:42) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand$$Lambda$7179/0x00000000f2c6eef0.accept(Unknown Source) ~[?:?]
	at org.samo_lego.taterzens.commands.NpcCommand.selectedTaterzenExecutor(NpcCommand.java:105) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand.interactWithBlock(ActionCommand.java:41) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand$$Lambda$5310/0x00000000f21186b8.run(Unknown Source) ~[?:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.server.command.CommandManager.execute(CommandManager:251) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.executeCommand(ServerPlayNetworkHandler:1222) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handleMessage(ServerPlayNetworkHandler:1206) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onGameMessage(ServerPlayNetworkHandler:1189) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:30) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:7) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.class_2600$$Lambda$6736/0x00000000f284ef88.run(Unknown Source) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:788) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:164) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:770) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:764) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:749) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zmi000$modifiedRunLoop(MinecraftServer:4399) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$6167/0x00000000cd699b90.run(Unknown Source) [intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:883) [?:?]
```

</details>

<details>

<summary> Exception on `/npc action interact` for Shulker Boxes (of any color) </summary>

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_7325()" because "â˜ƒ" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.37) ~[?:?]
	at net.minecraft.block.ShulkerBoxBlock.onUse(ShulkerBoxBlock:88) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:938) ~[?:?]
	at org.samo_lego.taterzens.npc.TaterzenNPC.interact(TaterzenNPC.java:1293) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand.lambda$interactWithBlock$2(ActionCommand.java:42) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand$$Lambda$7179/0x00000000f2c6eef0.accept(Unknown Source) ~[?:?]
	at org.samo_lego.taterzens.commands.NpcCommand.selectedTaterzenExecutor(NpcCommand.java:105) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand.interactWithBlock(ActionCommand.java:41) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand$$Lambda$5310/0x00000000f21186b8.run(Unknown Source) ~[?:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.server.command.CommandManager.execute(CommandManager:251) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.executeCommand(ServerPlayNetworkHandler:1222) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handleMessage(ServerPlayNetworkHandler:1206) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onGameMessage(ServerPlayNetworkHandler:1189) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:30) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:7) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.class_2600$$Lambda$6736/0x00000000f284ef88.run(Unknown Source) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:788) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:164) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:770) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:764) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:748) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zmi000$modifiedRunLoop(MinecraftServer:4399) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$6167/0x00000000cd699b90.run(Unknown Source) [intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:883) [?:?]
```

</details>

<details>

<summary> Exception on `/npc action interact` for Ender Chests </summary>

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_7274()" because "â˜ƒ" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.37) ~[?:?]
	at net.minecraft.block.EnderChestBlock.onUse(EnderChestBlock:80) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:938) ~[?:?]
	at org.samo_lego.taterzens.npc.TaterzenNPC.interact(TaterzenNPC.java:1293) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand.lambda$interactWithBlock$2(ActionCommand.java:42) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand$$Lambda$7179/0x00000000f2c6eef0.accept(Unknown Source) ~[?:?]
	at org.samo_lego.taterzens.commands.NpcCommand.selectedTaterzenExecutor(NpcCommand.java:105) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand.interactWithBlock(ActionCommand.java:41) ~[taterzens-1.3.0-fabric.jar:?]
	at org.samo_lego.taterzens.commands.ActionCommand$$Lambda$5310/0x00000000f21186b8.run(Unknown Source) ~[?:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.server.command.CommandManager.execute(CommandManager:251) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.executeCommand(ServerPlayNetworkHandler:1222) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.handleMessage(ServerPlayNetworkHandler:1206) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onGameMessage(ServerPlayNetworkHandler:1189) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:30) ~[?:?]
	at net.minecraft.network.packet.c2s.play.ChatMessageC2SPacket.apply(ChatMessageC2SPacket:7) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.class_2600$$Lambda$6736/0x00000000f284ef88.run(Unknown Source) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:788) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:164) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:770) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:764) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:749) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zmi000$modifiedRunLoop(MinecraftServer:4399) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$6167/0x00000000cd699b90.run(Unknown Source) [intermediary-minecraft-1.17.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:883) [?:?]
```

</details>

Edit (see above): Got the stack traces from reproducing this with Carpet installed and `/carpet superSecretSetting true'. The images are no longer needed and are therefore hidden.

Modlist:
```
Mods:
  [✔️] carpet-extra-1.17.1-1.4.43
  [✔️] disguiselib-1.0.5-fabric
  [✔️] fabric-api-0.37.2+1.17
  [✔️] fabric-carpet-1.17.1-1.4.45+v210811
  [❌] fabrictailor-1.6.1.jar (disabled)
  [✔️] fabrictailor-1.6.1+7fecdb3
  [✔️] notenoughcrashes-3.4.0+1.17-fabric
  [✔️] taterzens-1.3.0-fabric
```
Minecraft version: 1.17.1

**Comment by samolego** [comment]
Hi, thanks for report! I guess that BEs bdhave differently / expect PlayerEntity object
