### ISSUE TITLE
Unable to create NPCs

### ISSUE THREAD

**Issue by ClayBC** [samolego/Taterzens#45]
Attempting to use '/npc create' but keep getting met with "An unexpected error occurred when trying to execute that command." I have tried multiple different NPC names and variations. All other commands within the mod aren't giving any errors.

**Here is what is showing up in the server console:**
> [17:00:19] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: org.samo_lego.taterzens.npc.TaterzenNPC$1 cannot be cast to net.minecraft.entity.player.ServerPlayerEntity
Index: 5
Listeners:
0: HIGHEST
1: ASM: com.github.alexthe666.citadel.server.CitadelEvents@4de2a4e4 onAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
2: NORMAL
3: ASM: me.ichun.mods.hats.common.core.EventHandlerServer@4667eb29 onAttachCapabilitiesEntity(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
4: ASM: class tallestegg.bigbrain.BigBrainEvents onAttachEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
5: ASM: coffee.injected.improvedbackpacks.registry.IBCapabilities@290d8a1c attachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
6: ASM: class net.mehvahdjukaar.supplementaries.events.ServerEvents onAttachItemCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
7: ASM: class meldexun.better_diving.event.CapabilityEventHandler onAttachEntityCapabilitiesEvent(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
8: ASM: class meldexun.better_diving.event.CapabilityEventHandler onAttachCapabilitiesItemStackEvent(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
9: ASM: class com.infamous.sapience.mod.EventHandler onAttachEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
10: ASM: class com.infamous.dungeons_gear.capabilities.CapabilityHandler onAttachEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
11: ASM: class com.infamous.dungeons_gear.capabilities.CapabilityHandler onAttachItemCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
12: ASM: com.minecraftabnormals.abnormals_core.common.capability.chunkloading.ChunkLoaderEvents@2cf1491f attachChunkLoaderCap(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
13: ASM: class com.infamous.dungeons_mobs.MobEvents onAttachEntityCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
14: ASM: class artifacts.common.capability.swimhandler.SwimHandlerCapability$CapabilityEventHandler onAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
15: ASM: class artifacts.common.capability.killtracker.EntityKillTrackerCapability$CapabilityEventHandler onAttachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
16: ASM: class com.hollingsworth.arsnouveau.common.capability.ManaCapability$EventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
17: ASM: class com.hollingsworth.arsnouveau.api.familiar.FamiliarCap$EventHandler attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
18: net.minecraftforge.eventbus.EventBus$$Lambda$2699/1469738596@6ef63df5
19: ASM: class melonslise.subwild.common.event.SubWildForgeEvents attachCapabilitiesToWorld(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
20: net.minecraftforge.eventbus.EventBus$$Lambda$2699/1469738596@620ab508
21: ASM: class com.github.klikli_dev.occultism.handlers.CapabilityEventHandler onEntityConstructing(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
22: ASM: class com.simibubi.create.events.CommonEvents attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
23: ASM: class vazkii.quark.base.capability.CapabilityHandler attachItemCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
24: ASM: class vazkii.quark.base.capability.CapabilityHandler attachTileCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
25: ASM: class vazkii.quark.base.capability.CapabilityHandler attachWorldCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
26: ASM: vazkii.quark.content.automation.module.JukeboxAutomationModule@6e35ee56 attachCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
27: ASM: vazkii.quark.content.management.module.ShulkerBoxRightClickModule@edac1a2 onAttachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
28: ASM: vazkii.quark.content.tools.module.SeedPouchModule@48e2a4e0 onAttachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
29: ASM: vazkii.quark.content.tweaks.module.LavaBucketAsTrashModule@30746e1 onAttachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
30: ASM: tschipp.carryon.common.capabilities.event.PositionCommonEvents@6e93555d onAttachCaps(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
31: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@8c6843d attachEntitiesCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
32: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@8c6843d attachStackCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
33: net.minecraftforge.eventbus.EventBus$$Lambda$2699/1469738596@53a6f671
34: ASM: de.ellpeck.naturesaura.events.CommonEvents@a64352e onChunkCapsAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
35: ASM: de.ellpeck.naturesaura.events.CommonEvents@a64352e onWorldCapsAttach(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
36: ASM: top.theillusivec4.comforts.common.capability.CapabilitySleepData$CapabilityEvents@47e2daf2 attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
37: ASM: top.theillusivec4.curioofundying.CurioOfUndying@2e5330e attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
38: ASM: team.creative.playerrevive.server.ReviveEventServer@1f8ccdc7 attachCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
39: net.minecraftforge.eventbus.EventBus$$Lambda$2699/1469738596@6f04fb89
40: ASM: dev.gigaherz.toolbelt.slot.BeltExtensionSlot$AttachHandlers@56d24599 attachCapabilities(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
41: net.minecraftforge.eventbus.EventBus$$Lambda$2699/1469738596@30c27a09
42: net.minecraftforge.eventbus.EventBus$$Lambda$2699/1469738596@7573bec
43: net.minecraftforge.eventbus.EventBus$$Lambda$2699/1469738596@63264009
java.lang.ClassCastException: org.samo_lego.taterzens.npc.TaterzenNPC$1 cannot be cast to net.minecraft.entity.player.ServerPlayerEntity
at coffee.injected.improvedbackpacks.capability.player.BackpackUserProvider.<init>(BackpackUserProvider.kt:14)
at coffee.injected.improvedbackpacks.registry.IBCapabilities.attachCapability(IBCapabilities.kt:65)
at net.minecraftforge.eventbus.ASMEventHandler_69_IBCapabilities_attachCapability_AttachCapabilitiesEvent.invoke(.dynamic)
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:597)
at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:591)
at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:48)
at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:44)
at net.minecraft.entity.Entity.<init>(Entity.java:221)
at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:205)
at net.minecraft.entity.player.PlayerEntity.<init>(PlayerEntity.java:159)
at org.samo_lego.taterzens.npc.TaterzenNPC$1.<init>(TaterzenNPC.java:153)
at org.samo_lego.taterzens.npc.TaterzenNPC.<init>(TaterzenNPC.java:153)
at org.samo_lego.taterzens.api.TaterzensAPI.createTaterzen(TaterzensAPI.java:129)
at org.samo_lego.taterzens.api.TaterzensAPI.createTaterzen(TaterzensAPI.java:148)
at org.samo_lego.taterzens.commands.NpcCommand.spawnTaterzen(NpcCommand.java:1225)
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
at net.minecraft.command.Commands.func_197059_a(Commands.java:217)
at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1119)
at net.minecraft.network.play.ServerPlayNetHandler.func_244548_c(ServerPlayNetHandler.java:1102)
at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1081)
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36)
at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9)
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
at java.lang.Thread.run(Thread.java:748) 
> 
**Latest.log when attempting to use the command twice:**

> [03Sep2021 13:00:20.368] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.IllegalArgumentException: A team with the name '' already exists!
	at net.minecraft.scoreboard.Scoreboard.func_96527_f(SourceFile:188) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147247_a(ClientPlayNetHandler.java:1964) ~[?:?]
	at net.minecraft.network.play.server.STeamsPacket.func_148833_a(SourceFile:122) ~[?:?]
	at net.minecraft.network.play.server.STeamsPacket.func_148833_a(SourceFile:16) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$25048/1811542657.run(Unknown Source) ~[?:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$489/650797503.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[03Sep2021 13:00:20.370] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team ''.
	at net.minecraft.scoreboard.Scoreboard.func_96512_b(SourceFile:236) ~[?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147247_a(ClientPlayNetHandler.java:1995) ~[?:?]
	at net.minecraft.network.play.server.STeamsPacket.func_148833_a(SourceFile:122) ~[?:?]
	at net.minecraft.network.play.server.STeamsPacket.func_148833_a(SourceFile:16) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:36) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$25048/1811542657.run(Unknown Source) ~[?:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:189) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:151) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:128) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$489/650797503.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[03Sep2021 13:00:20.372] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] An unexpected error occurred trying to execute that command
> 

**Mod list:**
![image](https://user-images.githubusercontent.com/76756943/132042249-ab5eb5e8-46a6-4214-86b7-53dea43cd37f.png)
![image](https://user-images.githubusercontent.com/76756943/132042274-0ec9de73-db74-4f5f-91b3-1e523ce18164.png)
![image](https://user-images.githubusercontent.com/76756943/132042302-bf322441-57ed-4e7e-889b-96dd378c47d9.png)
![image](https://user-images.githubusercontent.com/76756943/132042347-57d7f5a4-a4a1-47b1-96de-ef536c23b313.png)

Any help would be appreciated, thank you for your time! :)

**Comment by samolego** [comment]
Humm, seems like mod is making assumption, try removing them in order like shown in server console log, starting with `com.github.alexthe666.citadel.server.CitadelEvents`
