### ISSUE TITLE
Taterzens and Chest Refill fail to start server when running together [Forge]

### ISSUE THREAD

**Issue by deadlymango** [samolego/Taterzens#81]
**Describe the bug**

Cannot run both Taterzens and Chest Refill at the same time

**Platform(s)**

- [] Fabric (did not test)
- [x] Forge

**Environment(s)**

- [] Singleplayer (did not test)
- [x] Server

**Versions**
* Minecraft 1.18.1
* Taterzens 1.8.1-forge

**To Reproduce**
1. Launch server with Taterzens and Chest Refill along with some other mods (in this case, mcwindows)
2. Immediately crash and fail to launch

**Expected behavior**
Server should start as normal.

**Logs**

https://pastebin.com/XNmq6avz 
before the crash: https://pastebin.com/2nPrNnTT 
<details>
  <summary>Logs</summary>
Exception in thread "main" java.lang.module.ResolutionException: Modules chestrefill and taterzens export package org.samo_lego.config2brigadier.command to module potionfoods
        at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
        at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
        at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
        at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
        at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)

</details>

**Additional context**

**Comment by samolego** [comment]
ohno, seems like a lib shadowing problem ...

**Comment by samolego** [comment]
Could you try with chestrefill 1.0.4?
